### PR TITLE
adds ubuntu user, tidies PATH, etc.

### LINKED ISSUE #5: set PATH for all users
In `Dockerfile`, setting `PATH` only affects `USER`.

### PR DESCRIPTION
**Pull request by dmalan**
Also fixes #5.

### CODE REVIEW

**Comment by dmalan** [comment]
@kzidane mind taking a look? This is a step toward making `cs50/cli` (and `cs50/server`) use `ubuntu` instead of `root`. I moved a few things that seem appropriate for interactive usage (as in `cs50/cli`) but not necessary for automated images like `cs50/server` and `cs50/ecs`.

**Comment by dmalan** [comment]
PS, let's not merge until I've tested `cs50/server` too.

**Comment by dmalan** [comment]
@kzidane, the `master` branches of `cs50/server` and `cs50/cli` are now both based on `cs50/baseimage:ubuntu`, so I think we're ready to merge `cs50/baseimage:ubuntu` into `cs50/baseimage:master`. But as soon as you do, can you also merge https://github.com/cs50/cli/pull/27 and https://github.com/cs50/ecs/pull/7, making sure we don't break ECS? :)

**Comment by kzidane** [comment]
k, I'll adjust deployment providers for Travis CI shortly! Thanks!

**Pull request merged**
